version: '3'

services:
  app:
    container_name: 999-multibots
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '2999:2999'
      - '3000:3000'
      - '3001:3001'
      - '3002:3002'
      - '3003:3003'
      - '3004:3004'
      - '3005:3005'
      - '3006:3006'
      - '3007:3007'
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: always
    networks:
      - bot_network

  nginx:
    container_name: bot-proxy
    image: nginx:latest
    ports:
      - '80:80'
      - '8443:443'
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - /etc/pki:/etc/pki
    depends_on:
      - app
    restart: always
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
