version: '3'

services:
  test-bot:
    container_name: simple-test-bot
    image: node:20-alpine
    working_dir: /app
    command: >
      sh -c "npm install telegraf && node bot-test.js"
    volumes:
      - ./bot-test.js:/app/bot-test.js
    restart: unless-stopped 