version: '3'

services:
  app:
    container_name: 999-multibots
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '2999:2999'
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: always
    networks:
      - bot_network

  nginx:
    container_name: bot-proxy
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - /etc/pki:/etc/pki
    depends_on:
      - app
    restart: always
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge 