version: '3.8'

services:
  webhook-bot:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: webhook-bot
    restart: always
    volumes:
      - ./.env:/app/.env
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - MODE=webhook
    ports:
      - '3001:3001'
    command: node dist/webhook.js

  nginx:
    image: nginx:latest
    container_name: bot-proxy
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - webhook-bot

networks:
  bot_network:
    driver: bridge
