services:
  app:
    container_name: 999-multibots
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '3001:3001'
      - '3002:3002'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - BOT_TOKEN=${TELEGRAM_BOT_TOKEN_PROD}
      - LOG_DIR=/var/logs
      - SECRET_KEY=${SECRET_KEY}
      - CREDENTIALS=${CREDENTIALS}
      - ORIGIN=${ORIGIN}
      - LOG_FORMAT=${LOG_FORMAT}
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - '8443:443'
      - '8080:80'
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge